### ISSUE TITLE
some question about config setting

### ISSUE THREAD

**Issue by zeynali** [algorithmiaio/sample-apps#10]
Hi ,
Firstly , Explain about batch_queue_capacity and num_readers in the config files ? what are these ? what are effect these in training ? 

secondly , why are you add this option in the config file ? num_readers: 2 and batch_queue_capacity=50

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/media/deepstorage/openimages/test_545.record"
  }
  label_map_path: "/home/zeryx/projects/openimages/annotations/label_map_545.pbtxt"
  shuffle: false
  num_readers: 2
}

**Comment by zeryx** [comment]
Hey zeynali! Good question.
`batch_queue_capacity` is the size of the `host memory` queue size. As the dataset is larger than what's available as system memory a stream buffer protocol must be used. This should be adjusted if your average datapoint is larger than what was defined in the tutorial - bare in mind it's not a 1:1 correlation between batch size & total host memory used.

`num_readers` is an interesting one, it seems to define the number of parallel data loaders for the host and GPU queue. We leave that in there as it's taken from the example protocol buffer, I definitely won't say I know exactly what it does.

Does that answer your question? If not feel free to re-open this later :smile:
