### ISSUE TITLE
The first call of save_data in process_metadata.py

### ISSUE THREAD

**Issue by tjliupeng** [algorithmiaio/sample-apps#3]
Hi,

The line 93 of process_metadata.py is:
`save_data(images, image_index_output_path)`

Here I think the first parameter shoulde be "filtered_images" instead of "images".

**Comment by zeryx** [comment]
Thanks for catching this tjliupeng, fixed.
https://github.com/algorithmiaio/sample-apps/commit/6156eaae55f41d46d0872196a92486aaa4baa4e3
