### ISSUE TITLE
translate_class_descriptions.py is incomplete

### ISSUE THREAD

**Issue by effnorwood** [algorithmiaio/sample-apps#4]
Git hub file translate_class_descriptions.py contains only 2 lines at the end which is incomplete:

if __name__ == '__main__':
    args = parser.parse_args()

Should be:
if __name__ == '__main__':
    args = parser.parse_args()
    trainable_classes_path = args.trainable_classes
    description_path = args.class_description
    translated_path = args.trainable_translated_path
    translated = translate_class_descriptions(trainable_classes_path, description_path)
    save_classes(translated, translated_path)

**Comment by zeryx** [comment]
corrected with https://github.com/algorithmiaio/sample-apps/commit/6dcadb47e0a878f6ce2ef4fba6ed5f4dcb581057

Thanks for pointing it out!
