### ISSUE TITLE
process_metadata.py appears stuck in loop

### ISSUE THREAD

**Issue by effnorwood** [algorithmiaio/sample-apps#5]
Ubuntu 16.04.3 LTS x64
Python 2.7.12
4 x CPU	: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
16GB RAM

process_metadata.py has been running for about 3 hours now at 100% CPU and has not completed. How long is it expected to take?

python process_metadata.py --annotations_input_path /data/open_images_detection/preprocessing/data/bbox_annotations/train/annotations-human-bbox.csv --image_index_input_path /data/open_images_detection/preprocessing/data/images/train/images.csv --point_output_path pointoutput.txt --image_index_output_path imageindex.txt --trainable_classes_path classes-trainable.txt 

grouping annotations: 100%|████████████████████████████████████████████████| 1238991/1238991 [00:03<00:00, 334964.65it/s]

<still running>

**Comment by zeryx** [comment]
Will investigate, thanks for your feedback!

**Comment by effnorwood** [comment]
Actually, close this one. It ended up finishing but I have no idea how long it took. Thanks!

**Comment by zeryx** [comment]
Ahh, good to know! in any case, I'll update the loops to have more useful tqdm outputs.

**Comment by zeryx** [comment]
updated with git: https://github.com/algorithmiaio/sample-apps/commit/a61e81dd34c6bc3d0dc6ad1a4087ae0124386625

The slowness is due to our filtering operation. It might make sense to map-reduce this across multiple cores, but for this tutorial, we decided to take the simplest approach here.
