### ISSUE TITLE
Translating Class Definitions Error

### ISSUE THREAD

**Issue by raagas** [algorithmiaio/sample-apps#6]
Hi,

I was following your post for object detection using TF object detection API. This is one of the most comprehensive post I came across. Thanks for posting it. 

But I'm getting error in Translating Class definition part. I'm using the following command:

`python translate_class_descriptions.py --trainable_classes_path /home/ragas/Documents/DNN/Object_detection/algorithmia/data/classes/classes-trainable.txt --class_description_path /home/ragas/Documents/DNN/Object_detection/algorithmia/data/classes/class-descriptions.csv --trainable_translated_path /home/ragas/Documents/DNN/Object_detection/algorithmia/data/`

And I'm  getting this error:

`Traceback (most recent call last):
  File "translate_class_descriptions.py", line 36, in <module>
    translated = translate_class_descriptions(trainable_classes_path, description_path)
  File "translate_class_descriptions.py", line 8, in translate_class_descriptions
    trainable_classes = file.read().replace(' ', '').split('\n')
TypeError: a bytes-like object is required, not 'str'
`

Could you please guide me, if I'm missing something?

Thanks!

**Comment by jamesatha** [comment]
Out of curiosity, what version of python are you using?

**Comment by raagas** [comment]
Hi Jamesath,

I'm using python 3.6 + tf 1.3 GPU (tf 1.4 still don't have GPU support, so using older version) & Ubuntu.

Thanks!

**Comment by jamesatha** [comment]
Alright, thanks for the info. It looks like this is an issue with python 2 vs python 3. (I was able to get this working with python 2 and I get the same error with python 3). 

Any chance you can use python 2 for now?

**Comment by raagas** [comment]
@jamesatha: Thanks for figuring it out! No. I want to stick with python 3 as it's the future. Python 2 will go out of support by 2020. Let me also look into it. I didn't expect it to be python version issue. I thought I made some silly mistake.

Thanks again!

**Comment by jamesatha** [comment]
Alright, I think I have a fix that should get you unblocked with python3 for now. It's a one-change in how you open the file: https://github.com/algorithmiaio/sample-apps/commit/ecb9900c0b10cd6561dc6175351ad894acffb61f
Let me know if that works for you

**Comment by raagas** [comment]
Solved the first part. Changed `with open(trainable_classes_file, 'rb') as file` to `with open(trainable_classes_file, 'r') as file`. The whole code is:

`def translate_class_descriptions(trainable_classes_file, descriptions_file):
    with open(trainable_classes_file, 'r') as file:
        trainable_classes = file.read().replace(' ', '').split('\n')
    description_table = {}
    with open(descriptions_file) as f:
        for row in csv.reader(f):
            if len(row):
                description_table[row[0]] = row[1].replace("\"", "").replace("'", "").replace('`', '')
    output = []
    for elm in trainable_classes:
        if elm != '':
            output.append(description_table[elm])
    return output
`

The call portion is :

`python translate_class_descriptions.py --trainable_classes_path /home/ragas/Documents/DNN/Object_detection/algorithmia/data/classes/classes-trainable.txt --class_description_path /home/ragas/Documents/DNN/Object_detection/algorithmia/data/classes/class-descriptions.csv --trainable_translated_path /home/ragas/Documents/DNN/Object_detection/algorithmia/data/classes/ab.txt`

Just want to confirm that I'm generating a new text file in the execusion ("ab.txt") in my case. Is it ok or I need to assign some other file?

**Comment by jamesatha** [comment]
Nice, looks like you came to the same solution I did ('r' should be the same as 'rt')

And yes, you'll create a new file at whatever path you specify in the `--trainable_translated_path`. Be careful, since it will overwrite that file if it exists already

**Comment by raagas** [comment]
Thanks @jamesatha! You had been really helpful. If I could complete this post. I'll share the entire code with you. Then you have a version with python 3 as well! This is a really good and extremely detailed post.

Thanks again!
