### ISSUE TITLE
speed up your code

### ISSUE THREAD

**Issue by shanenian** [algorithmiaio/sample-apps#7]
hello, 

if you can change https://github.com/algorithmiaio/sample-apps/blob/master/deep_dive_demos/open_images_detection/preprocessing/process_metadata.py#L49 to "if element['id'] in set(ids):", your code can run much faster. Maybe I am wrong, please reconsider.

Thanks!

**Comment by zeryx** [comment]
Thanks for the tip shanenian! Updated in 791e4c375994cd2bda810ab5672259e2df5e59b4
